// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


/*! 
 * @file BatteryState.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */
#ifndef _SENSOR_MSGS_BATTERY_STATE_HPP_
#define _SENSOR_MSGS_BATTERY_STATE_HPP_


#include "micrortps.hpp"
#include <topic_config.h>
#include <topic.hpp>


#include "std_msgs/Header.hpp"

namespace sensor_msgs {

enum BatteryStatus
{
  POWER_SUPPLY_STATUS_UNKNOWN = 0,
  POWER_SUPPLY_STATUS_CHARGING,
  POWER_SUPPLY_STATUS_DISCHARGING,
  POWER_SUPPLY_STATUS_NOT_CHARGING,
  POWER_SUPPLY_STATUS_FULL
};

enum BatteryHealth
{
  POWER_SUPPLY_HEALTH_UNKNOWN = 0,
  POWER_SUPPLY_HEALTH_GOOD,
  POWER_SUPPLY_HEALTH_OVERHEAT,
  POWER_SUPPLY_HEALTH_DEAD,
  POWER_SUPPLY_HEALTH_OVERVOLTAGE,
  POWER_SUPPLY_HEALTH_UNSPEC_FAILURE,
  POWER_SUPPLY_HEALTH_COLD,
  POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE,
  POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE
};

enum BatteryTechnology
{
  POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0,
  POWER_SUPPLY_TECHNOLOGY_NIMH,
  POWER_SUPPLY_TECHNOLOGY_LION,
  POWER_SUPPLY_TECHNOLOGY_LIPO,
  POWER_SUPPLY_TECHNOLOGY_LIFE,
  POWER_SUPPLY_TECHNOLOGY_NICD,
  POWER_SUPPLY_TECHNOLOGY_LIMN
};


class BatteryState : public ros2::Topic<BatteryState>
{
public: 
    std_msgs::Header header;
    float voltage;
    float current;
    float charge;
    float capacity;
    float design_capacity;
    float percentage;
    uint8_t power_supply_status;
    uint8_t power_supply_health;
    uint8_t power_supply_technology;
    bool present;
    float* cell_voltage;
    uint32_t cell_voltage_size;
    char location[255];
    char serial_number[255];

  BatteryState():
    Topic("sensor_msgs::msg::dds_::BatteryState_", SENSOR_MSGS_BATTERY_STATE_TOPIC),
    header(),
    voltage(0), current(0), charge(0), capacity(0), design_capacity(0), percentage(0),
    power_supply_status(0), power_supply_health(0), power_supply_technology(0),
    present(0), cell_voltage(NULL), cell_voltage_size(0)
  { 
  }

  bool serialize(struct MicroBuffer* writer, const BatteryState* topic)
  {
    (void) header.serialize(writer, &topic->header);
    (void) serialize_float(writer, topic->voltage);
    (void) serialize_float(writer, topic->current);
    (void) serialize_float(writer, topic->charge);
    (void) serialize_float(writer, topic->capacity);
    (void) serialize_float(writer, topic->design_capacity);
    (void) serialize_float(writer, topic->percentage);
    (void) serialize_uint8_t(writer, topic->power_supply_status);
    (void) serialize_uint8_t(writer, topic->power_supply_health);
    (void) serialize_uint8_t(writer, topic->power_supply_technology);
    (void) serialize_bool(writer, topic->present);
    (void) serialize_sequence_float(writer, topic->cell_voltage, topic->cell_voltage_size);
    (void) serialize_sequence_char(writer, topic->location, (uint32_t)(strlen(topic->location) + 1));
    (void) serialize_sequence_char(writer, topic->serial_number, (uint32_t)(strlen(topic->serial_number) + 1));

    return writer->error == BUFFER_OK;
  }

  bool deserialize(struct MicroBuffer* reader, BatteryState* topic)
  {
    uint32_t size_location = 0;
    uint32_t size_serial_number = 0;

    (void) header.deserialize(reader, &topic->header);
    (void) deserialize_float(reader, &topic->voltage);
    (void) deserialize_float(reader, &topic->current);
    (void) deserialize_float(reader, &topic->charge);
    (void) deserialize_float(reader, &topic->capacity);
    (void) deserialize_float(reader, &topic->design_capacity);
    (void) deserialize_float(reader, &topic->percentage);
    (void) deserialize_uint8_t(reader, &topic->power_supply_status);
    (void) deserialize_uint8_t(reader, &topic->power_supply_health);
    (void) deserialize_uint8_t(reader, &topic->power_supply_technology);
    (void) deserialize_bool(reader, &topic->present);
    (void) deserialize_sequence_float(reader, topic->cell_voltage, &topic->cell_voltage_size);
    (void) deserialize_sequence_char(reader, topic->location, &size_location);
    (void) deserialize_sequence_char(reader, topic->serial_number, &size_serial_number);

    return reader->error == BUFFER_OK;
  }

  uint32_t size_of_topic(const BatteryState* topic, uint32_t size)
  {
    size  = header.size_of_topic(&topic->header, size);

    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);

    size += 1 + get_alignment(size, 1);
    size += 1 + get_alignment(size, 1);
    size += 1 + get_alignment(size, 1);
    size += 1 + get_alignment(size, 1);

    size += 4 + get_alignment(size, 4);
    size += (topic->cell_voltage_size * 4) + get_alignment(size, 4);

    size += 4 + get_alignment(size, 4) + (uint32_t)(strlen(topic->location) + 1);
    size += 4 + get_alignment(size, 4) + (uint32_t)(strlen(topic->serial_number) + 1);

    return size;
  }

};

} // namespace sensor_msgs


#endif // _SENSOR_MSGS_BATTERY_STATE_HPP_
