// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


/*! 
 * @file LaserScan.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */
#ifndef _SENSOR_MSGS_LASER_SCAN_HPP_
#define _SENSOR_MSGS_LASER_SCAN_HPP_


#include "micrortps.hpp"
#include <topic_config.h>
#include <topic.hpp>


#include "std_msgs/Header.hpp"

namespace sensor_msgs {


class LaserScan : public ros2::Topic<LaserScan>
{
public: 
    std_msgs::Header header;
    float angle_min;
    float angle_max;
    float angle_increment;
    float time_increment;
    float scan_time;
    float range_min;
    float range_max;
    float* ranges;
    uint32_t ranges_size;
    float* intensities;
    uint32_t intensities_size;

  LaserScan():
    Topic("sensor_msgs::msg::dds_::LaserScan_", SENSOR_MSGS_LASER_SCAN_TOPIC),
    header(),
    angle_min(0), angle_max(0), angle_increment(0), time_increment(0),
    scan_time(0), range_min(0), range_max(0),
    ranges(NULL), ranges_size(0),
    intensities(NULL), intensities_size(0)
  { 
  }

  bool serialize(struct MicroBuffer* writer, const LaserScan* topic)
  {
    (void) header.serialize(writer, &topic->header);
    (void) serialize_float(writer, topic->angle_min);
    (void) serialize_float(writer, topic->angle_max);
    (void) serialize_float(writer, topic->angle_increment);
    (void) serialize_float(writer, topic->time_increment);
    (void) serialize_float(writer, topic->scan_time);
    (void) serialize_float(writer, topic->range_min);
    (void) serialize_float(writer, topic->range_max);
    (void) serialize_sequence_float(writer, topic->ranges, topic->ranges_size);
    (void) serialize_sequence_float(writer, topic->intensities, topic->intensities_size);

    return writer->error == BUFFER_OK;
  }

  bool deserialize(struct MicroBuffer* reader, LaserScan* topic)
  {
    (void) header.deserialize(reader, &topic->header);
    (void) deserialize_float(reader, &topic->angle_min);
    (void) deserialize_float(reader, &topic->angle_max);
    (void) deserialize_float(reader, &topic->angle_increment);
    (void) deserialize_float(reader, &topic->time_increment);
    (void) deserialize_float(reader, &topic->scan_time);
    (void) deserialize_float(reader, &topic->range_min);
    (void) deserialize_float(reader, &topic->range_max);
    (void) deserialize_sequence_float(reader, topic->ranges, &topic->ranges_size);
    (void) deserialize_sequence_float(reader, topic->intensities, &topic->intensities_size);

    return reader->error == BUFFER_OK;
  }

  uint32_t size_of_topic(const LaserScan* topic, uint32_t size)
  {
    size  = header.size_of_topic(&topic->header, size);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += (topic->ranges_size * 4) + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += (topic->intensities_size * 4) + get_alignment(size, 4);

    return size;
  }

};

} // namespace sensor_msgs


#endif // _SENSOR_MSGS_LASER_SCAN_HPP_
