#ifndef SKETCH_USER_CONFIG_H_
#define SKETCH_USER_CONFIG_H_

#define USER_ENABLE_TRANSPORT_UDP
// #define USER_ENABLE_TRANSPORT_TCP
// #define USER_ENABLE_TRANSPORT_SERIAL

#define UXR_CREATE_ENTITIES_USING_REF  0
#define USER_ROS2_PUBLISHER_MAX        5
#define USER_ROS2_SUBSCRIBER_MAX       5

#endif /* SKETCH_USER_CONFIG_H_ */