// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


/*! 
 * @file KeyValue.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */
#ifndef _DIAGNOSTIC_MSGS_KEY_VALUE_HPP_
#define _DIAGNOSTIC_MSGS_KEY_VALUE_HPP_


#include "micrortps.hpp"
#include <topic_config.h>
#include <topic.hpp>


namespace diagnostic_msgs {

class KeyValue : public ros2::Topic<KeyValue>
{
public: 
    char key[255];
    char value[255];

  KeyValue():
    Topic("diagnostic_msgs::msg::dds_::KeyValue_", DIAGNOSTIC_MSGS_KEY_VALUE_TOPIC)
  { 
  }

  bool serialize(struct MicroBuffer* writer, const KeyValue* topic)
  {
    (void) serialize_sequence_char(writer, topic->key, (uint32_t)(strlen(topic->key) + 1));
    (void) serialize_sequence_char(writer, topic->value, (uint32_t)(strlen(topic->value) + 1));
   
    return writer->error == BUFFER_OK;
  }

  bool deserialize(struct MicroBuffer* reader, KeyValue* topic)
  {
    uint32_t size_key = 0;
    uint32_t size_value = 0;

    (void) deserialize_sequence_char(reader, topic->key, &size_key);
    (void) deserialize_sequence_char(reader, topic->value, &size_value);
    
    return reader->error == BUFFER_OK;
  }

  uint32_t size_of_topic(const KeyValue* topic, uint32_t size)
  {
    size += 4 + get_alignment(size, 4) + (uint32_t)(strlen(topic->key) + 1);
    size += 4 + get_alignment(size, 4) + (uint32_t)(strlen(topic->value) + 1);

    return size;
  }

};

} // namespace diagnostic_msgs


#endif // _DIAGNOSTIC_MSGS_KEY_VALUE_HPP_
