#ifndef ROS2ARDUINO_USER_CONFIG_H_
#define ROS2ARDUINO_USER_CONFIG_H_

//#define USER_DISABLE_UDP_TRANSPORT
//#define USER_DISABLE_TCP_TRANSPORT
//#define USER_DISABLE_SERIAL_TRANSPORT

#define UXR_CREATE_ENTITIES_USING_REF  0
#define USER_ROS2_PUBLISHER_MAX        10
#define USER_ROS2_SUBSCRIBER_MAX       10


#endif /* ROS2ARDUINO_USER_CONFIG_H_ */
