// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


/*! 
 * @file SensorState.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */
#ifndef _TURTLEBOT3_MSGS_SENSOR_STATE_HPP_
#define _TURTLEBOT3_MSGS_SENSOR_STATE_HPP_


#include "micrortps.hpp"
#include <topic_config.h>
#include <topic.hpp>


#include "std_msgs/Header.hpp"

namespace turtlebot3_msgs {


class SensorState : public ros2::Topic<SensorState>
{
public: 
    std_msgs::Header header;
    uint8_t bumper;
    float cliff;
    float sonar;
    float illumination;
    uint8_t led;
    uint8_t button;
    bool torque;
    int32_t left_encoder;
    int32_t right_encoder;
    float battery;

  SensorState():
    Topic("turtlebot3_msgs::msg::dds_::SensorState_", TURTLEBOT3_MSGS_SENSOR_STATE_TOPIC),
    header(),
    bumper(0), cliff(0), sonar(0), illumination(0), led(0), button(0),
    torque(0), left_encoder(0), right_encoder(0), battery(0)
  { 
  }

  bool serialize(struct MicroBuffer* writer, const SensorState* topic)
  {
    (void) header.serialize(writer, &topic->header);
    (void) serialize_uint8_t(writer, topic->bumper);
    (void) serialize_float(writer, topic->cliff);
    (void) serialize_float(writer, topic->sonar);
    (void) serialize_float(writer, topic->illumination);
    (void) serialize_uint8_t(writer, topic->led);
    (void) serialize_uint8_t(writer, topic->button);
    (void) serialize_bool(writer, topic->torque);
    (void) serialize_int32_t(writer, topic->left_encoder);
    (void) serialize_int32_t(writer, topic->right_encoder);
    (void) serialize_float(writer, topic->battery);

    return writer->error == BUFFER_OK;
  }

  bool deserialize(struct MicroBuffer* reader, SensorState* topic)
  {
    (void) header.deserialize(reader, &topic->header);
    (void) deserialize_uint8_t(reader, &topic->bumper);
    (void) deserialize_float(reader, &topic->cliff);
    (void) deserialize_float(reader, &topic->sonar);
    (void) deserialize_float(reader, &topic->illumination);
    (void) deserialize_uint8_t(reader, &topic->led);
    (void) deserialize_uint8_t(reader, &topic->button);
    (void) deserialize_bool(reader, &topic->torque);
    (void) deserialize_int32_t(reader, &topic->left_encoder);
    (void) deserialize_int32_t(reader, &topic->right_encoder);
    (void) deserialize_float(reader, &topic->battery);

    return reader->error == BUFFER_OK;
  }

  virtual uint32_t size_of_topic(const SensorState* topic, uint32_t size)
  {
    size  = header.size_of_topic(&topic->header, size);
    size += 1 + get_alignment(size, 1);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 1 + get_alignment(size, 1);
    size += 1 + get_alignment(size, 1);
    size += 1 + get_alignment(size, 1);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    
    return size;
  }

};

} // namespace turtlebot3_msgs


#endif // _TURTLEBOT3_MSGS_SENSOR_STATE_HPP_
